# Generated by Django 5.1.6 on 2025-03-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_moviefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviefeedback',
            name='rating',
            field=models.CharField(choices=[('0', 'Dislike'), ('1', 'Like')], default='0', max_length=1),
        ),
    ]
