# Generated by Django 5.1.6 on 2025-03-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_moviefeedback_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviefeedback',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
